version: '3'
services:
    app:
        build:
            context: .
        container_name: noted_app
        volumes:
            - ./noted:/noted
        ports:
            - 8000:8000
        networks:
            - noted-network
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres
        restart: always
        tty: true
        container_name: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - noted-network
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "sh -c 'pg_isready -U $DATABASE_USER} -d ${DATABASE_NAME}'"
                ]
            interval: 10s
            timeout: 3s
            retries: 3

    redis:
        image: redis
        container_name: redis
        networks:
            - noted-network
        ports:
            - 6379:6379
        depends_on:
            - postgres
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
networks:
    noted-network:
